name: Run npm build

on:
  pull_request:
    branches: ['main']
  release: 
    types: [published, unpublished]
  push:
    branches: ['main]


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '16.x'

      - name: npm install, build
        run: |
          npm install
          npm run build
